GRANT ALL PRIVILEGES ON db1.* TO 'LZCWGZ'@'192.168.10.135' IDENTIFIED BY '123456';
FLUSH PRIVILEGES;

USE db1;
CREATE TABLE IF NOT EXISTS example_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
